export interface Project {
  id: string;
  title: string;
  shortDescription: string;
  overview: string;
  problem: string;
  solution: string;
  features: string[];
  techStack: string[];
  image: string;
  gallery: string[];
  github?: string;
  liveDemo?: string;
  badge?: string;
}

export const projects: Project[] = [
  {
    id: 'smart-campus-attendance',
    title: 'Smart Campus Attendance System',
    shortDescription:
      'A QR-based attendance system for campus-wide tracking, reporting, and analytics.',
    overview:
      'A complete attendance management platform designed for universities — students scan QR codes generated by faculty, and the system records, validates, and reports attendance in real time.',
    problem:
      'Manual attendance is slow, error-prone, and produces no usable data. Universities needed a faster, more accurate way to track student presence across multiple sections.',
    solution:
      'Built a secure system that issues rotating QR codes per session, validates scans server-side, and surfaces analytics to faculty and admins through a clean dashboard.',
    features: [
      'Rotating QR codes per class session',
      'Real-time attendance validation',
      'Faculty & admin dashboards',
      'Attendance analytics & exports',
      'Role-based authentication',
      'Audit log for every scan',
    ],
    techStack: ['PHP', 'MySQL', 'JavaScript', 'Tailwind CSS', 'Chart.js'],
    image: '/projects/smart-campus.svg',
    gallery: ['/projects/smart-campus.svg', '/projects/smart-campus-2.svg'],
    github: 'https://github.com/jeanmarcaguilar/smart-campus-attendance',
    badge: 'Capstone',
  },
  {
    id: 'blockchain-ecommerce',
    title: 'Blockchain E-Commerce Web Application',
    shortDescription:
      'A decentralized e-commerce experience using smart contracts for transparent transactions.',
    overview:
      'An e-commerce prototype where product authenticity and order settlement are enforced on-chain, giving buyers verifiable proof of purchase and sellers reduced disputes.',
    problem:
      'Traditional e-commerce has no transparent dispute layer; counterfeit goods and chargebacks erode trust between buyers and sellers.',
    solution:
      'Used Solidity smart contracts to handle escrow-style order settlement, with a React front-end connecting through MetaMask for transaction signing.',
    features: [
      'Smart-contract escrow payments',
      'MetaMask wallet integration',
      'Product provenance records',
      'Order & dispute tracking',
      'Verified seller profiles',
    ],
    techStack: ['Solidity', 'React', 'Tailwind CSS', 'Ethers.js', 'MetaMask'],
    image: '/projects/blockchain-ecommerce.svg',
    gallery: ['/projects/blockchain-ecommerce.svg'],
    github: 'https://github.com/jeanmarcaguilar/blockchain-ecommerce',
    badge: 'Blockchain',
  },
  {
    id: 'parking-management',
    title: 'Parking Management System',
    shortDescription:
      'A web app that streamlines parking slot allocation, billing, and reporting for operators.',
    overview:
      'An internal tool for parking operators to manage slots, vehicles, and billing — replacing spreadsheets with a centralized, auditable system.',
    problem:
      'Small-to-medium parking operators relied on pen-and-paper logs that made billing, disputes, and occupancy reporting painful and slow.',
    solution:
      'Delivered a web-based management console with slot tracking, automated billing, and printable reports — designed for non-technical staff.',
    features: [
      'Real-time slot tracking',
      'Automated billing & receipts',
      'Vehicle history lookup',
      'Role-based operator accounts',
      'Printable daily reports',
    ],
    techStack: ['PHP', 'MySQL', 'Bootstrap', 'JavaScript'],
    image: '/projects/parking.svg',
    gallery: ['/projects/parking.svg'],
    github: 'https://github.com/jeanmarcaguilar/parking-management',
    badge: 'Academic',
  },
  {
    id: 'loan-management',
    title: 'Loan Management System',
    shortDescription:
      'A platform for managing loan applications, approvals, repayment schedules, and reports.',
    overview:
      'A web application that digitizes the loan lifecycle — from application, to approval, to structured repayment tracking — for small lending institutions.',
    problem:
      'Small lending offices tracked loans in spreadsheets, leading to missed payments and difficulty producing financial summaries.',
    solution:
      'Built a structured loan workflow with role-based approval, repayment schedules, and visual dashboards summarizing portfolio health.',
    features: [
      'Loan application workflow',
      'Approval & disbursement tracking',
      'Automated repayment schedules',
      'Borrower history lookup',
      'Portfolio dashboard',
    ],
    techStack: ['PHP', 'MySQL', 'JavaScript', 'Bootstrap'],
    image: '/projects/loan.svg',
    gallery: ['/projects/loan.svg'],
    github: 'https://github.com/jeanmarcaguilar/loan-management',
    badge: 'Academic',
  },
  {
    id: 'portfolio-website',
    title: 'Portfolio Website',
    shortDescription:
      'The very site you are viewing — built with React, TypeScript, Tailwind, and Framer Motion.',
    overview:
      'A personal portfolio designed to feel like a product — fast, accessible, and quiet on the eye. Engineered with reusable components, lazy loading, and clean separation of concerns.',
    problem:
      'Most portfolio templates either look generic or fight the developer when changes are needed. The goal was to build something genuinely maintainable.',
    solution:
      'Composed the site from small, focused components and reusable animation primitives. Kept the visual language restrained and the design tokens centralized in Tailwind.',
    features: [
      'Fully responsive across breakpoints',
      'Subtle Framer Motion entrance animations',
      'EmailJS-powered contact form',
      'Modular component architecture',
      'Accessibility-first markup',
    ],
    techStack: ['React', 'TypeScript', 'Vite', 'Tailwind CSS', 'Framer Motion'],
    image: '/projects/portfolio.svg',
    gallery: ['/projects/portfolio.svg'],
    github: 'https://github.com/jeanmarcaguilar/portfolio',
    liveDemo: 'https://jeanmarc.dev',
    badge: 'Personal',
  },
];
